name: Build executables
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  Build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Build for Windows
      run: npm run electron:build
    - name: Create zip
      run: Compress-Archive dist_electron/SML.exe SML-win.zip 
    - uses: actions/upload-artifact@v3
      with:
        name: sml-win
        path: SML-win.zip
  Build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Build for Linux
      run: npm run electron:build -- --publish never
    - name: Create zip
      run: zip -r SML-lnx.zip dist_electron/SML
    - uses: actions/upload-artifact@v3
      with:
        name: sml-lnx
        path: SML-lnx.zip
  Build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Build for MacOS
      run: npm run electron:build -- --publish never
    - name: Create zip
      run: zip -r SML-mac.zip dist_electron/mac
    - uses: actions/upload-artifact@v3
      with:
        name: sml-mac
        path: SML-mac.zip
